### ISSUE TITLE
How to change some parameters in maxwell2d

### ISSUE THREAD

**Issue by tako861225** [pyansys/pyaedt#1080]
How to change the parameters in Excitations if there is already assign value before ?
1. number of conductors 
![image](https://user-images.githubusercontent.com/51187903/164983688-fb954bf7-6a6b-4f13-9bac-6263676d4d3c.png)
I tried to reassign , but it not work .
![image](https://user-images.githubusercontent.com/51187903/164983798-8e2e6790-7357-4fd3-bb67-23dbc6bc4dc4.png)
2. parameters in winding 
![image](https://user-images.githubusercontent.com/51187903/164983864-079f627e-e180-447b-9104-23a6f03c0752.png)
I would like to change the type and others , but I don't know how QQ
I tried to reassign , but it not work too.

thanks lot 
Evelyn

**Comment by tako861225** [comment]
I try the update instruction. It will return "True" but nothing change , both ``assign_winding`` and ``assign_coil``
![image](https://user-images.githubusercontent.com/51187903/165036247-f5bb7734-9ecc-4130-973c-e82047864f10.png)

**Comment by Samuelopez-ansys** [comment]
Hi Evelyn,

Which version of pyaedt are you using?

I have tested the winding in the last pyaedt release, and it works:

bounds = aedtapp.assign_winding(current_value=20e-3, coil_terminals=["Coil"])
bounds.props["Type"] = "Voltage"
bounds.props["Current"] = "0.01A"

![image](https://user-images.githubusercontent.com/85613111/165110240-d5719958-1fd5-418d-ad50-7e5cc464cdaf.png)


You don't need bounds.update() anymore, it is automatically updated.

**Comment by tako861225** [comment]
Thanks for the respond ❤️ 
I use the latest version of pyaedt.
I notice that props.[""] should use name on GUI ,not the functions parameters name.
 (I change it from "winding_type" to "Type")
But in assing_coil ,the function will return ``CoilObject``  that I couldn't find the explanation about it.
 
![image](https://user-images.githubusercontent.com/51187903/165113117-e7c1490b-561e-42a4-9063-9ded460e7585.png)

I try the same way to update the parameters but it doesn't work .
![image](https://user-images.githubusercontent.com/51187903/165114083-351584dc-6053-4618-994b-274f4d416528.png)
![image](https://user-images.githubusercontent.com/51187903/165114235-e6bdd78e-1c6d-4c6c-82d7-152e5f35a9ed.png)

**Comment by Samuelopez-ansys** [comment]
Hi Evelyn,

This is not the way of using this method.

1. You should put a list as input_object, as you attached, input_object is a list of objects or face IDs:
        bounds = aedtapp.assign_coil(input_object=["Coil"])

2. The properties could have different names because internally the method could have different output properties, so you should check the different output properties:
![image](https://user-images.githubusercontent.com/85613111/165116950-76564e4f-7545-43af-8114-0aed6972908d.png)


Then you can play with them:
bounds.props["Conductor number"] = "3"
bounds.props["PolarityType"] = "Negative"

Let me know if it is clear and if it works in your case.
