### ISSUE TITLE
Add ...For Q3D, we would like to obtain the solution data for all the passes, not just the last one. Can you show us the syntax to get it using API? For example, there are three passes in below screenshot.

### ISSUE THREAD

**Issue by priti-ashvin-shah-ibm** [pyansys/pyaedt#1675]
### Description of the feature

For Q3D, we would like to obtain the solution data for all the passes, not just the last one. Can you show us the syntax to get it using API? For example, there are three passes in below screenshot.

![image](https://user-images.githubusercontent.com/74020801/189134672-135334c2-1dd9-4ea0-ab91-11971e1d4d99.png)

@obrienpja , @Samuelopez-ansys , @ThomasGM4

### Useful links and references

Issue #1650 has helpful snippets to get the last pass.  
#1676, #1677

**Comment by Samuelopez-ansys** [comment]
Hi @priti-ashvin-shah-ibm 

Sorry for the delay.

The only way I found to obtain this info is:

from pyaedt import Q3d
app = Q3d(specified_version="2022.2")


a = app.post.get_solution_data(expressions=all_C_matrices, context="Original", setup_sweep_name="Setup1: AdaptivePass",
                               variations={"Pass": ["All"]})

a.active_intrinsic["Pass"] = 2
c2 = a.data_real()

a.active_intrinsic["Pass"] = 3
c3 = a.data_real()

You will get the data at different passes.

In a.intrinsics you will get all possible variations (Passes) so I think it is very easy to implement a loop to obtain all the data at different passes.

Let me know if it is what you need.

Regards

**Comment by priti-ashvin-shah-ibm** [comment]
Can you share the link/documentation for syntax to use get_solution_data?

Since the data could converge before max_pass is reached.  Is there a way to determine how many passes are available before entering the loop for each pass?  I am guessing that ` cap_data.intrinsics['Pass']` will do that.

When  I execute the below code.  Then compare the different passes, unfortunately, all_cap_data[pass_int] give the same data.  I used the information from both issue threads to write the below method.  Do you have some insight???


```
def get_capacitance_all_passes(self, setup_name: str):

        all_C_matrices = self.current_app.matrices[0].get_sources_for_plot()

        setup_sweep_name = f'{setup_name}: AdaptivePass'
        cap_data = self.current_app.post.get_solution_data(
            expressions=all_C_matrices,
            context="Original",
            setup_sweep_name=setup_sweep_name,
            variations={"Pass": ["All"]})

        cap_data.active_intrinsic['Freq']  # Is 5.0


        all_cap_data = Dict()
        for item in cap_data.intrinsics['Pass']:
            pass_int = int(item)
            cap_data.active_intrinsic["Pass"] = int(pass_int)
            all_cap_data[pass_int] = cap_data._solution_data_real()
```

Also, I would like to have for each pass the entire matrix as shown in image.
![image](https://user-images.githubusercontent.com/74020801/189716015-4c355df1-fb71-4590-ac06-a7c7f96ac318.png)

**Comment by Samuelopez-ansys** [comment]
Hi @priti-ashvin-shah-ibm ,

Indeed, _cap_data.intrinsics['Pass']_ will give you the passes, in my dummy example:
![image](https://user-images.githubusercontent.com/85613111/189868121-ef8e669b-a9ed-4b21-b344-2d4c590bbb2b.png)

The usage of "active_intrinsic" is only valid for the current active results. For example this operation:
_cap_data.active_intrinsic["Pass"] = 1_

It is only applied to the current value: 
_cap_data.data_real()_

The method __solution_data_real(_) is a private method that should not be used. Private methods are methods that public methods are used for some operations. In this case, is the only way to get with one single command all the data, but we are going to expose it as a public method in future releases, but we are starting now the enhancement, I will let you know once we finish.

In summary, __solution_data_real()_ gets all the results and you could access this info with a similar loop (you see how the first row correspond to the frequency and the second to the passes):

![image](https://user-images.githubusercontent.com/85613111/189869490-9803173e-6ea2-458e-8bc3-d3f60854f4cd.png)

But again, we are going to develop a new method to get all the results in a more simple way.

The documentation of this method is:
https://aedt.docs.pyansys.com/API/_autosummary/pyaedt.modules.AdvancedPostProcessing.PostProcessor.get_solution_data.html?highlight=get_solution_data

But it is a 'complex' method because it can be used in all AEDT apps (Icepak, HFSS...) so it is very general, I found useful debugging to find the best way of using it for each specific case.

Please let me know if my answer was clear.

Regards

**Comment by priti-ashvin-shah-ibm** [comment]
Also, what would be expected behaviour if the data converges before getting to max_pass?

**Comment by Samuelopez-ansys** [comment]
Hi @priti-ashvin-shah-ibm,

Checking the picture, I see a different value for each pass. I can see it on this line for example:
![image](https://user-images.githubusercontent.com/85613111/190357146-294d1c79-0935-4649-9efd-b06b0651a4fc.png)

It is a dictionary where each key is a different Pass, (5.0, 1.0) is the Freq 5.0 and Pass 1, (5.0, 2.0) is the Freq 5 and pass 2....

For that reason a public method will give easier access to this info, if we wait for the last PR Massimo did, I think accessing this data will be much easier. I will give you the commands for using it once the PR is closed.

About your second question, it is returning nan. In my previous message, you could see the nan values.

Regards

**Comment by priti-ashvin-shah-ibm** [comment]
Hi @Samuelopez-ansys ,
Thank you for finding the difference.  I missed that.  

I will hold off until Massimo's pull request is merged.  Thank you for your offer regarding, "I will give you the commands for using it once the PR is closed."  Hopefully documentation will also updated with examples. 

Regarding convergence, nan works for me.

**Comment by Samuelopez-ansys** [comment]
Hi @priti-ashvin-shah-ibm,

The PR is merged in the main.

Let me describe the new features.

First of all, you could check the available reports using:

current_app.post.available_quantities_categories()

current_app.post.available_report_quantities()

I think it is interesting to check which reports are available for each application.

Now, again doing:

_current_app = Q3d(specified_version="2022.2")
all_C_matrices = current_app.matrices[0].get_sources_for_plot()
cap_data = current_app.post.get_solution_data(expressions=all_C_matrices, context="Original", setup_sweep_name="Setup1: AdaptivePass", variations={"Pass": ["All"]})_

You will get 2 new properties "full_matrix_mag_phase" and "full_matrix_real_imag":

![image](https://user-images.githubusercontent.com/85613111/190446178-b3991829-de74-46f9-bd4f-98868bb875d7.png)

This will give you all available data directly without accessing to the private method.

And finally... you could activate pandas :)

By default is deactivated, but you have 2 options to activate it:

1) Before opening the application:
from pyaedt import settings
settings.enable_pandas_output = True

Ant then perform all data obtained with get_solution_data will have pandas format.

2) Activate it on the current data:
cap_data.enable_pandas_output = True
![image](https://user-images.githubusercontent.com/85613111/190447446-5c73cbe5-0030-4afa-ba30-8613599a5d3a.png)

Please let us know if is what you expected, and close the issues.

Regards,
Samuel

**Comment by priti-ashvin-shah-ibm** [comment]
Thank you for your update.  This looks very promising.  I am going to a conference next week.  I may not get to it before I leave.  If not, please understand if there is a delayed response.

**Comment by priti-ashvin-shah-ibm** [comment]
Hi @Samuelopez-ansys , I got a chance to look at this merge.  I have two lines of thoughts.  I used the below method:


```
def get_capacitance_all_passes(self, setup_name: str):

        all_C_matrices = self.current_app.matrices[0].get_sources_for_plot()

        setup_sweep_name = f'{setup_name}: AdaptivePass'
        cap_data = self.current_app.post.get_solution_data(
            expressions=all_C_matrices,
            context="Original",
            setup_sweep_name=setup_sweep_name,
            variations={"Pass": ["All"]})

        # Pandas output should have been set prior to opening Ansys,
        # however, just confirming if changed by user through GUI.
        cap_data.enable_pandas_output = True
        confirm_freq = cap_data.active_intrinsic['Freq']  # Is 5.0

        all_cap_data = Dict()
        for item in cap_data.intrinsics['Pass']:
            pass_int = int(item)  #float to int
            cap_data.active_intrinsic["Pass"] = pass_int
            #all_cap_data[pass_int] = cap_data.full_matrix_real_imag
            all_cap_data[pass_int] = cap_data.full_matrix_mag_phase

        c1_units = cap_data.units_data
        _ = 5  # for breakpoint


```

- I just want to confirm that I don't need the for loop when using enable_pandas_output = True. The current example, has dataframe with three rows.  Which I believe represent each pass.

-  The image below shows all_cap_data  for my example I am working on.   Based on image I shared  at the start of this issue,  the data appears to be originally, in some kind of table like numpy or dataframe,

The latest commit, returns a dataframe which appears to be, one line for each pass. I would like a 2d format for each pass, which is similar to what one would see in the GUI. It seems like someone took the 2D data and made it 1D for pandas output.  

Can I make a request for different format?

For example a list:  zeroth entry is the freq, the 1st entry is 2-d dataframe for 1st pass , 2nd entry is 2-d dataframe for 2nd pass.  I am requesting this since it appears the data appears to be originally in 2-D in Ansys.  The current commit on repo would require every user to receive one row for each pass, then build a 2-d dataframe based on the column names.

![image](https://user-images.githubusercontent.com/74020801/192637755-c127beb0-b734-4e2f-aac2-8c6f136048d6.png)

**Comment by Samuelopez-ansys** [comment]
Hi @priti-ashvin-shah-ibm ,

For now, we can not perform this modification because it is very specific for Q3D.

When you activate Pandas, pyaedt return the same data but with pandas format, for now we can not refactor the output format because this method is used in many AEDT apps (Icepak, Maxwell...).

If you need this format, you will need for now to reorganize the data. For example, the following code tries to define the format as you suggested:

_all_cap_data_magnitude = []

all_cap_data_magnitude_dict = {}

cont = 0
for f in cap_data.intrinsics['Freq']:
    all_cap_data_magnitude.append(f)
    for item in cap_data.intrinsics['Pass']:
        all_cap_data_magnitude.append(cap_data.full_matrix_mag_phase[0].iloc[int(item)-1])
    all_cap_data_magnitude_dict[cont] = all_cap_data_magnitude
    cont += 1_


I defined a dictionary in which each key will correspond to a frequency (if more than 1 exists). Then on each frequency, you will have a list, the first element is the frequency, the 2nd a Serie (Pandas format) with the first pass data, 3rd with the second Pass....

![image](https://user-images.githubusercontent.com/85613111/192987999-fd3563af-dfcf-49bc-8ab4-498688df30da.png)

I think it is the format you need to make your script easier to use, but for now, PyAEDT can not add new formats because we are still maintaining IronPython.

Of course, PyAEDT is opensource code and you are free (and I would like to see it 👍 ) to modify PyAEDT and improve this part if you see it could be implemented in a general way.

Let me know if you need anything else :)

**Comment by priti-ashvin-shah-ibm** [comment]
@Samuelopez-ansys , thank you for giving pandas output and explaining your reasoning .  I wanted to, at least, request what would be helpful for us.  For now we can close this issue.

**Comment by priti-ashvin-shah-ibm** [comment]
> 

I think you had indents in the code snippet.  For others, you may want to edit post to format as code, vs text.
