### ISSUE TITLE
Is osmnx being used for testing?

### ISSUE THREAD

**Issue by akaszynski** [pyansys/pyaedt#2339]
https://github.com/pyansys/pyaedt/blob/017e4c582a25842a991a0421d2c535f5248f3b89/requirements/requirements_test.txt#L8

**Comment by MaxJPRey** [comment]
@akaszynski Yes it is. For instance we are using it coupled with SBR+ to simulate signal in streets.
We have some tests for those features in our testing suites.
`osmnx` is part of our `extra-requirement` too and because people might not have installed those one on their machine to perform tests.
We thought about adding it in the requirements_test to make sure it is not disrupting local testing. Same goes for the documentation.
