### ISSUE TITLE
Bug located in hfss.boundaries

### ISSUE THREAD

**Issue by fwlfHS** [pyansys/pyaedt#2762]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

`hfss.boundaries` returns an empty list, whereas `hfss.oboundary.GetBoundariesOfType('Radiation')` returns the correct boundary name inside a list. and `hfss.modeler.get_boundaries_name()` works as well.

using pyaedt v0.6.59 with of AEDT 2023.1

### Steps To Reproduce

`hfss.boundaries` 

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.9

### Installed packages

-

**Comment by maxcapodi78** [comment]
@fwlfHS Pyaedt is retrieving such information from the project file or stored when the command is executed from pyaedt.
In your case maybe you have created the boundary manually and not saved the project.
Try to save the project and read the boundaries value again.

**Comment by fwlfHS** [comment]
Thanks Massimo, this was indeed the case. Is there a method to check whether a project has been saved and if not to interactively ask the user for a destination?

**Comment by Samuelopez-ansys** [comment]
@fwlfHS The default destination is the same than in AEDT projects (Options>General Options>Directories), then if the user doesn't specify any path, the project will be saved there. 

You could use different methods to check if the path exists or not:

from pyaedt.generic.general_methods import check_if_path_exists
check_if_path_exists(path)

or you could check the project timestamp:
hfss.project_time_stamp

Each time you save the project, the time_stamp will change, then you could verify if the project has been saved since the last time stamp.

Let us know if it helps and if this issue could be closed.

**Comment by fwlfHS** [comment]
Thanks Samuel, this can be closed.
