### ISSUE TITLE
sweep.add_subrange() Bug

### ISSUE THREAD

**Issue by linmingchih** [pyansys/pyaedt#707]
line 1283 of pyaedt/pyaedt/modules/SetupTemplates.py is wrong, it should be:
            range["RangeEnd"] = str(end) + unit
Maybe you can put the line out of if-else.

![image](https://user-images.githubusercontent.com/13580731/149050777-a071e33e-4359-48d1-8f8c-0cbb50b4f355.png)

**Comment by MaxJPRey** [comment]
@linmingchih,

This will be fixed in the PR #715 .

However regarding the suggestion of taking `range["RangeEnd"] = str(end) + unit` out of the if/else blocks, we can't because `end` is an optional parameter and not use in the case of `SinglePoints`. In that case `range["RangeEnd"] = str(start) + unit`.

Thanks for your valuable feedback,

Maxime.
