### ISSUE TITLE
'NoneType' object has no attribute 'GetModule'

### ISSUE THREAD

**Issue by amirh92** [pyansys/pyaedt#759]
I intended to run a  given simulation which implemented in Maxwell2d. I encountered 'NoneType' object has no attribute 'GetModule' error from site-packages\pyaedt\application\Analysis.py", line 106.
```python
self._ooptimetrics = self._odesign.GetModule("Optimetrics")
self._ooutput_variable = self._odesign.GetModule("OutputVariable")
```

**Comment by amirh92** [comment]
please check this procedure for opening existed simulation. there are a lot of errors that point to the NoneType object having no attribute.

**Comment by maxcapodi78** [comment]
@amirh92  can you share a piece of code that reproduce this issue so I can identify the issue?

**Comment by amirh92** [comment]
@maxcapodi78 I'm using the last version of pyaedt. thanks for your help.
My project was created with the previous version of aedt. so after opening it with 2022R1 and saving it, my problem was solved.

**Comment by amirh92** [comment]
@maxcapodi78 So it works once. after running again the code, I encountered this error
![image](https://user-images.githubusercontent.com/95634739/151012587-815752c2-498c-4044-a4e5-c608b0c48bdc.png)

**Comment by maxcapodi78** [comment]
@amirh92 my file is from Examples folder. Can you provide me the file or tell me from which version the project comes?

**Comment by maxcapodi78** [comment]
Here the problem is that odesign is not populated and I need to understand why. odesign is created following his steps:
1 I check if a design is present and if is present 
   a. if I passed a design name I check if it exists and if it is of the expected type (maxwell2d in your case)
   b. if a solution type is passed I check if design exists and if it is of expected type
   c. if none of above a new design is created
2. if a design is not present a new design is created
now if you can send me at least the project structure ( a snapshot of project tree is enough) I'll try to reproduce it.
