### ISSUE TITLE
Support '.obj' format in FieldAnalysis3D.export_3d_model()

### ISSUE THREAD

**Issue by linmingchih** [pyansys/pyaedt#840]
The .obj format is not supported in FieldAnalysis3D.export_3d_model(). It will be great if you can add it in \pyaedt\application\Analysis3D.py line 488:

        elif fileFormat == '.obj':
            self.modeler.oeditor.ExportModelMeshToFile(os.path.join(filePath, fileName + fileFormat), allObjects)

The reason is that ModelPlotter.add_object() in pyaedt.generic.plot.py seems only support .obj format. Thanks.

**Comment by linmingchih** [comment]
Hi Massimo

hfss.plot() can't support orientation setting that ModelPlotter.plot can support. Or you can add orientation in hfss.plot()? Thanks.

**Comment by Samuelopez-ansys** [comment]
Hi @linmingchih ,

I am going to close this issue because as Massimo said, with hfss.plot() you could control the orientation and other properties:
![image](https://user-images.githubusercontent.com/85613111/187403250-0b48d6d3-7299-45e1-8075-6ff7a753f6bc.png)

You need to create the plot with 'show' to False, modify the properties and then show it :
my_plot = hfss.plot(show=False, plot_air_objects=False)
my_plot.show_axes = False
my_plot.show_grid = False
my_plot.isometric_view = False
my_plot.camera_position = "xy"
my_plot.off_screen = False
my_plot.plot()
