### ISSUE TITLE
Maxwell2D : How to change the value of Model Depth ?

### ISSUE THREAD

**Issue by Siderpan** [pyansys/pyaedt#888]
Hello,
I want to change the value of ```Model Depth```

![image](https://user-images.githubusercontent.com/89152981/155342833-4e169786-f020-4b99-92f1-0eb93b010af7.png)

However the most relevant function I found was ```Maxwell2d.model_depth```
But it seems that this function can only get model depth.

![image](https://user-images.githubusercontent.com/89152981/155344468-bd5dc620-7126-4b2c-812a-2a01b0d35701.png)

How to set the model depth in Maxwell 2D Transient type ?

Thanks a lot,
Jason

**Comment by Samuelopez-ansys** [comment]
Hi @Siderpan ,

You just need to type:

maxwell_2d.model_depth = 5.0

And you will modify the value. We will change the help because these methods allow Get and Set the value:
![Capture](https://user-images.githubusercontent.com/85613111/155479926-3256bad8-bfa9-4402-831b-9d8747bca8a5.PNG)

Let us know if it works for closing the Issue

**Comment by Siderpan** [comment]
Hi @Samuelopez-ansys ,

It does work !!

Thanks for your response 👍
